<a href="https://colab.research.google.com/github/brainmentorspvtltd/IGDTU_PyTorchTraining/blob/main/IG_PyTorchIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'2.0.1+cu118'

In [3]:
x = np.array([[1,2,4],[6,4,8],[6,6,8],[7,9,2]])

In [4]:
x

array([[1, 2, 4],
       [6, 4, 8],
       [6, 6, 8],
       [7, 9, 2]])

In [5]:
x.shape

(4, 3)

In [6]:
type(x)

numpy.ndarray

In [7]:
data = [[1,2,4],[6,4,8],[6,6,8],[7,9,2]]
x_tensor = torch.tensor(data)

In [8]:
x_tensor

tensor([[1, 2, 4],
        [6, 4, 8],
        [6, 6, 8],
        [7, 9, 2]])

In [9]:
x_tensor.size()

torch.Size([4, 3])

In [10]:
scalar = torch.tensor(5)

In [11]:
scalar

tensor(5)

In [12]:
scalar.item()

5

In [13]:
vector = torch.tensor([5,9])

In [14]:
vector

tensor([5, 9])

In [15]:
vector.shape

torch.Size([2])

In [16]:
# scalar - single number
# vector - 1D array
# matrix - 2D array
# tensor - ND array

In [17]:
torch.zeros(6)

tensor([0., 0., 0., 0., 0., 0.])

In [18]:
torch.zeros((4,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [20]:
torch.ones((4,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
torch.rand(6)

tensor([0.4235, 0.9867, 0.1130, 0.1979, 0.9913, 0.2205])

In [22]:
torch.rand((4,6))

tensor([[0.2925, 0.5150, 0.7559, 0.6973, 0.7615, 0.5120],
        [0.5214, 0.6433, 0.5067, 0.4473, 0.4579, 0.4259],
        [0.5113, 0.5406, 0.2779, 0.3001, 0.4060, 0.9743],
        [0.8738, 0.3804, 0.7816, 0.8400, 0.5101, 0.4744]])

In [23]:
x = torch.rand((4,6))

In [24]:
x.shape

torch.Size([4, 6])

In [25]:
x.dtype

torch.float32

In [26]:
x.device

device(type='cpu')

In [27]:
tensor = torch.tensor([4,7,8])

In [28]:
tensor

tensor([4, 7, 8])

In [29]:
tensor + 5

tensor([ 9, 12, 13])

In [30]:
tensor * 5

tensor([20, 35, 40])

In [32]:
tensor_2 = torch.tensor([1,2,3])

In [33]:
tensor + tensor_2

tensor([ 5,  9, 11])

In [34]:
tensor * tensor_2

tensor([ 4, 14, 24])

In [35]:
x = torch.tensor([
    [1,2,3,4],
    [5,4,6,6],
    [1,5,3,7]
])

y = torch.tensor([
    [9,21,13,14],
    [1,7,4,2],
    [1,5,3,7]
])

In [36]:
x + y

tensor([[10, 23, 16, 18],
        [ 6, 11, 10,  8],
        [ 2, 10,  6, 14]])

In [37]:
x * y

tensor([[ 9, 42, 39, 56],
        [ 5, 28, 24, 12],
        [ 1, 25,  9, 49]])

In [43]:
%%time
x @ y.T

CPU times: user 1.33 ms, sys: 21 µs, total: 1.35 ms
Wall time: 6.31 ms


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [40]:
%%time
torch.matmul(x, y.T)

CPU times: user 777 µs, sys: 0 ns, total: 777 µs
Wall time: 626 µs


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [44]:
%%time
torch.mm(x, y.T)

CPU times: user 1.19 ms, sys: 12 µs, total: 1.2 ms
Wall time: 3.36 ms


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [61]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
torch.linspace(1,100,20)

tensor([  1.0000,   6.2105,  11.4211,  16.6316,  21.8421,  27.0526,  32.2632,
         37.4737,  42.6842,  47.8947,  53.1053,  58.3158,  63.5263,  68.7368,
         73.9474,  79.1579,  84.3684,  89.5789,  94.7895, 100.0000])

In [56]:
torch.randint(1,10,size=(3,4))

tensor([[2, 7, 3, 3],
        [2, 4, 7, 4],
        [1, 8, 6, 3]])

In [62]:
x = torch.randint(1,100,size=(20,))

In [63]:
x

tensor([17, 97, 51, 70, 50, 10, 75, 38, 71, 71, 53, 17, 26, 75, 23, 25, 65, 91,
        91, 35])

In [64]:
x.min()

tensor(10)

In [65]:
x.max()

tensor(97)

In [66]:
x.sum()

tensor(1051)

In [68]:
x.type(torch.float32).mean()

tensor(52.5500)

In [69]:
x = torch.randint(1,50,size=(24,))

In [70]:
x.shape

torch.Size([24])

In [71]:
x.reshape(4,6)

tensor([[48, 40,  8, 28, 19, 25],
        [ 9, 16, 10,  6, 46, 33],
        [19, 47, 23, 44, 18, 17],
        [39, 36, 41, 34,  4, 16]])

In [72]:
x.view(6,4)

tensor([[48, 40,  8, 28],
        [19, 25,  9, 16],
        [10,  6, 46, 33],
        [19, 47, 23, 44],
        [18, 17, 39, 36],
        [41, 34,  4, 16]])

In [74]:
x = x.reshape(4,6)

In [75]:
x[0]

tensor([48, 40,  8, 28, 19, 25])

In [76]:
x[:, 0]

tensor([48,  9, 19, 39])

In [77]:
x[0:3,0:2]

tensor([[48, 40],
        [ 9, 16],
        [19, 47]])