<a href="https://colab.research.google.com/github/brainmentorspvtltd/IGDTU_PyTorchTraining/blob/main/IG_PyTorchIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'2.0.1+cu118'

In [3]:
x = np.array([[1,2,4],[6,4,8],[6,6,8],[7,9,2]])

In [4]:
x

array([[1, 2, 4],
       [6, 4, 8],
       [6, 6, 8],
       [7, 9, 2]])

In [5]:
x.shape

(4, 3)

In [6]:
type(x)

numpy.ndarray

In [7]:
data = [[1,2,4],[6,4,8],[6,6,8],[7,9,2]]
x_tensor = torch.tensor(data)

In [8]:
x_tensor

tensor([[1, 2, 4],
        [6, 4, 8],
        [6, 6, 8],
        [7, 9, 2]])

In [10]:
x_tensor.size()

torch.Size([4, 3])

In [12]:
scalar = torch.tensor(5)

In [13]:
scalar

tensor(5)

In [14]:
scalar.item()

5

In [15]:
vector = torch.tensor([5,9])

In [16]:
vector

tensor([5, 9])

In [17]:
vector.shape

torch.Size([2])

In [18]:
# scalar - single number
# vector - 1D array
# matrix - 2D array
# tensor - ND array

In [19]:
torch.zeros(6)

tensor([0., 0., 0., 0., 0., 0.])

In [20]:
torch.zeros((4,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [22]:
torch.ones((4,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
torch.rand(6)

tensor([0.9818, 0.8084, 0.8113, 0.6614, 0.1512, 0.6913])

In [24]:
torch.rand((4,6))

tensor([[0.3347, 0.1167, 0.4415, 0.7083, 0.7209, 0.1025],
        [0.4036, 0.6639, 0.0138, 0.6711, 0.5139, 0.4468],
        [0.5759, 0.9540, 0.1765, 0.9476, 0.3521, 0.0714],
        [0.8310, 0.7922, 0.6276, 0.1725, 0.0398, 0.5843]])

In [25]:
x = torch.rand((4,6))

In [26]:
x.shape

torch.Size([4, 6])

In [27]:
x.dtype

torch.float32

In [28]:
x.device

device(type='cpu')