<a href="https://colab.research.google.com/github/brainmentorspvtltd/IGDTU_PyTorchTraining/blob/main/IG_SimpleANN_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

In [3]:
# Activation function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [4]:
x.shape

(3, 4)

In [19]:
# input layer neurons will be always equals to the number of columns
inputNeurons = x.shape[1]
# hidden neurons we can decide by hit and trial
hiddenNeurons = 3
# output neurons depends on number of classes we have in target column
outputNeurons = 1

In [20]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1, hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1, outputNeurons))

In [21]:
# Feedforward
# Step-1 - apply dot product and add bias : f(x) = x.wh + biasHidden
fx = np.dot(x, weightsHidden) + biasHidden

In [22]:
# Step-2 - apply activation function
hiddenLayer = sigmoid(fx)

In [23]:
hiddenLayer

array([[0.90603389, 0.65352473, 0.84106858],
       [0.94801038, 0.80386861, 0.90161074],
       [0.87469198, 0.74645775, 0.83265015]])

In [24]:
# Step-3 - apply dot product and add bias : f(x) = hiddenLayer.wout + biasOut
fx_ = np.dot(hiddenLayer, weightsOutput) + biasOutput

In [25]:
fx_

array([[1.01176489],
       [1.06777636],
       [0.99822071]])

In [26]:
biasHidden

array([[0.655772  , 0.09431517, 0.71017051]])

In [27]:
biasOutput

array([[0.16026501]])

In [31]:
outputLayer = sigmoid(fx_)

In [29]:
outputLayer

array([[0.7333654 ],
       [0.74417381],
       [0.7307086 ]])

In [32]:
def derivativeSigmoid(x):
  return x * (1 - x)

In [33]:
# Backpropagation

# Error on output layer
errorOutput = outputLayer - y
# Slope on output layer - derivative of activation function applied on this layer
slopeOutput = derivativeSigmoid(outputLayer)
# Delta = error x slope
deltaOutput = errorOutput * slopeOutput

In [35]:
errorHidden = np.dot(deltaOutput, weightsOutput.T)
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden