<a href="https://colab.research.google.com/github/brainmentorspvtltd/IGDTU_PyTorchTraining/blob/main/IG_SimpleANN_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

In [ ]:
# Activation function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [ ]:
x.shape

(3, 4)

In [33]:
# input layer neurons will be always equals to the number of columns
inputNeurons = x.shape[1]
# hidden neurons we can decide by hit and trial
hiddenNeurons = 4
# output neurons depends on number of classes we have in target column
outputNeurons = 1

In [34]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1, hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1, outputNeurons))

In [35]:
# Feedforward
# Step-1 - apply dot product and add bias : f(x) = x.wh + biasHidden
fx = np.dot(x, weightsHidden) + biasHidden

In [36]:
# Step-2 - apply activation function
hiddenLayer = sigmoid(fx)

In [37]:
hiddenLayer

array([[0.8976489 , 0.82175358, 0.76421968, 0.87760047],
       [0.9034121 , 0.83175904, 0.86016566, 0.94825009],
       [0.80963327, 0.71796918, 0.84220111, 0.93052533]])

In [38]:
# Step-3 - apply dot product and add bias : f(x) = hiddenLayer.wout + biasOut
fx_ = np.dot(hiddenLayer, weightsOutput) + biasOutput

In [39]:
fx_

array([[2.30764531],
       [2.42234053],
       [2.27339111]])

In [40]:
biasHidden

array([[0.80951327, 0.20155262, 0.33867043, 0.85186221]])

In [41]:
biasOutput

array([[0.41622712]])

In [42]:
outputLayer = sigmoid(fx_)

In [43]:
outputLayer

array([[0.90950824],
       [0.91851509],
       [0.9066492 ]])

In [44]:
def derivativeSigmoid(x):
  return x * (1 - x)

In [45]:
# Backpropagation

# Error on output layer
errorOutput = outputLayer - y
# Slope on output layer - derivative of activation function applied on this layer
slopeOutput = derivativeSigmoid(outputLayer)
# Delta = error x slope
deltaOutput = errorOutput * slopeOutput

In [46]:
errorHidden = np.dot(deltaOutput, weightsOutput.T)
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden

In [47]:
errorOutput

array([[-0.09049176],
       [-0.08148491],
       [ 0.9066492 ]])

In [20]:
alpha = 0.01
weightsOutput = weightsOutput - hiddenLayer.T.dot(deltaOutput) * alpha
weightsHidden = weightsHidden - x.T.dot(deltaHidden) * alpha
biasOutput = biasOutput - np.sum(deltaOutput) * alpha
biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [30]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1, hiddenNeurons))
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1, outputNeurons))

In [31]:
alpha = 0.01
epochs = 30000

for i in range(epochs):
  # Feedforward
  # Step-1 - apply dot product and add bias : f(x) = x.wh + biasHidden
  fx = np.dot(x, weightsHidden) + biasHidden
  # Step-2 - apply activation function
  hiddenLayer = sigmoid(fx)
  # Step-3 - apply dot product and add bias : f(x) = hiddenLayer.wout + biasOut
  fx_ = np.dot(hiddenLayer, weightsOutput) + biasOutput
  # Step-4 - apply activation on output layer
  outputLayer = sigmoid(fx_)
  # Backpropagation - calculate loss + optimization of weights and bias
  # Error on output layer
  errorOutput = outputLayer - y
  # Slope on output layer - derivative of activation function applied on this layer
  slopeOutput = derivativeSigmoid(outputLayer)
  # Delta = error x slope
  deltaOutput = errorOutput * slopeOutput
  errorHidden = np.dot(deltaOutput, weightsOutput.T)
  slopeHidden = derivativeSigmoid(hiddenLayer)
  deltaHidden = errorHidden * slopeHidden
  # Optimization - weights update
  weightsOutput = weightsOutput - hiddenLayer.T.dot(deltaOutput) * alpha
  weightsHidden = weightsHidden - x.T.dot(deltaHidden) * alpha
  biasOutput = biasOutput - np.sum(deltaOutput) * alpha
  biasHidden = biasHidden - np.sum(deltaHidden) * alpha

In [32]:
outputLayer

array([[0.97538884],
       [0.95586403],
       [0.06126862]])